# Generated by Django 5.1.3 on 2024-11-23 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('race_class', models.CharField(choices=[('F1', 'Formula 1'), ('F2', 'Formula 2'), ('F3', 'Formula 3'), ('Rally', 'Rally'), ('Moto', 'Moto'), ('Karting', 'Karting')], max_length=10)),
                ('date', models.DateTimeField()),
                ('age_limit', models.IntegerField(default=18)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('photo', models.ImageField(upload_to='race_photos/')),
                ('registered_users', models.ManyToManyField(blank=True, related_name='registered_races', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('comment_type', models.CharField(choices=[('question', 'Question'), ('review', 'Review'), ('cooperation', 'Cooperation')], max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.race')),
            ],
        ),
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('car_description', models.TextField(blank=True)),
                ('experience', models.IntegerField(default=0)),
                ('class_type', models.CharField(choices=[('F1', 'Formula 1'), ('F2', 'Formula 2'), ('F3', 'Formula 3'), ('Rally', 'Rally'), ('Moto', 'Moto'), ('Karting', 'Karting')], max_length=10)),
                ('birth_date', models.DateField()),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RaceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.race')),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.racer')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_time', models.DurationField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.race')),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.racer')),
            ],
        ),
    ]
