# Generated by Django 5.1.3 on 2024-11-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_remove_race_photo_race_image_race_is_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='registered_users',
        ),
        migrations.AddField(
            model_name='race',
            name='registered_racers',
            field=models.ManyToManyField(blank=True, related_name='registered_races', to='races.racer'),
        ),
    ]
