site_name: WEB-programming Documentation
nav:
  - Home: index.md
  - Лабораторные:
      - №1: lw1/report_1.md
      - №2: lw2/report_2.md
      - №3: lw3/report_3.md
  - Практики:
      - №3.1: pw3_1/report_3_1.md
      - №3.2: pw3_2/report_3_2.md
theme:
  name: mkdocs
  color_mode: dark
  user_color_mode_toggle: true
